---
abstract: 'Is a shop is open or closed at this moment?'
author:
  - 'Peter Stuifzand <peter@stuifzand.eu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-OpeningHours
requires:
  DateTime: 0
version: 0.4.0
